"""empty message

Revision ID: 20b57403ce08
Revises: dfa81572dd8a
Create Date: 2022-06-11 10:25:22.197010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20b57403ce08'
down_revision = 'dfa81572dd8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'MembersModel', 'GroupsModel', ['groups_id'], ['id'])
    op.drop_column('MembersModel', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MembersModel', sa.Column('date', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'MembersModel', type_='foreignkey')
    # ### end Alembic commands ###
