"""empty message

Revision ID: 2a53395ca0af
Revises: 20b57403ce08
Create Date: 2022-06-12 09:27:15.481658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a53395ca0af'
down_revision = '20b57403ce08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MembersModel', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MembersModel', 'date')
    # ### end Alembic commands ###
