"""empty message

Revision ID: 326b72b1f510
Revises: fc6f256d19c4
Create Date: 2022-06-12 12:40:07.184317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326b72b1f510'
down_revision = 'fc6f256d19c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_post', sa.Column('title', sa.Unicode(), nullable=True))
    op.add_column('tb_post', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('tb_post', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tb_post', 'tb_users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'tb_post', 'tb_groups', ['group_id'], ['id'])
    op.drop_column('tb_post', 'name')
    op.drop_column('tb_post', 'image')
    op.drop_column('tb_post', 'sku')
    op.drop_column('tb_post', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_post', sa.Column('price', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('tb_post', sa.Column('sku', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tb_post', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tb_post', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tb_post', type_='foreignkey')
    op.drop_constraint(None, 'tb_post', type_='foreignkey')
    op.drop_column('tb_post', 'group_id')
    op.drop_column('tb_post', 'user_id')
    op.drop_column('tb_post', 'title')
    # ### end Alembic commands ###
