"""empty message

Revision ID: 9228d42c6a4c
Revises: c5c04006cd8a
Create Date: 2022-06-12 10:06:34.804195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9228d42c6a4c'
down_revision = 'c5c04006cd8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UsersModel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('email', sa.Unicode(), nullable=True),
    sa.Column('password', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.Unicode(), nullable=True),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('price', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('GroupsModel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin', sa.Integer(), nullable=True),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['admin'], ['UsersModel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('MembersModel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('groups_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['groups_id'], ['GroupsModel.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['UsersModel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MembersModel')
    op.drop_table('GroupsModel')
    op.drop_table('post')
    op.drop_table('UsersModel')
    # ### end Alembic commands ###
