"""empty message

Revision ID: d8e19ad4183d
Revises: 
Create Date: 2022-06-10 17:36:52.539523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8e19ad4183d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UsersModel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('email', sa.Unicode(), nullable=True),
    sa.Column('password', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.Unicode(), nullable=True),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('price', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('GroupsModel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin', sa.Integer(), nullable=True),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['admin'], ['UsersModel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('MembersModel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_group', sa.Integer(), nullable=True),
    sa.Column('id_member', sa.Integer(), nullable=True),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('groups_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_member'], ['post.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['UsersModel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MembersModel')
    op.drop_table('GroupsModel')
    op.drop_table('post')
    op.drop_table('UsersModel')
    # ### end Alembic commands ###
