"""empty message

Revision ID: dfa81572dd8a
Revises: d8e19ad4183d
Create Date: 2022-06-10 17:42:57.351833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfa81572dd8a'
down_revision = 'd8e19ad4183d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('GroupsModel', sa.Column('members', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'GroupsModel', 'MembersModel', ['members'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'GroupsModel', type_='foreignkey')
    op.drop_column('GroupsModel', 'members')
    # ### end Alembic commands ###
