"""empty message

Revision ID: fd7f172535a7
Revises: d6f1249ada05
Create Date: 2022-06-12 09:49:40.023856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd7f172535a7'
down_revision = 'd6f1249ada05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('email', sa.Unicode(), nullable=True),
    sa.Column('password', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('UsersModel')
    op.drop_constraint('GroupsModel_admin_fkey', 'GroupsModel', type_='foreignkey')
    op.create_foreign_key(None, 'GroupsModel', 'tb_users', ['admin'], ['id'])
    op.drop_constraint('MembersModel_users_id_fkey', 'MembersModel', type_='foreignkey')
    op.create_foreign_key(None, 'MembersModel', 'tb_users', ['users_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'MembersModel', type_='foreignkey')
    op.create_foreign_key('MembersModel_users_id_fkey', 'MembersModel', 'UsersModel', ['users_id'], ['id'])
    op.drop_constraint(None, 'GroupsModel', type_='foreignkey')
    op.create_foreign_key('GroupsModel_admin_fkey', 'GroupsModel', 'UsersModel', ['admin'], ['id'])
    op.create_table('UsersModel',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"UsersModel_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='UsersModel_pkey')
    )
    op.drop_table('tb_users')
    # ### end Alembic commands ###
